name: Build

on:
  pull_request:
    branches: [ prod ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create mock env
      run: touch .env
    - name: Build
      run: make docker
  
  cargo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

