name: Docker

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ prod ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create mock env
      run: touch .env
    - name: Build
      run: make docker
